---
- name: Add EE Cloud Services Execution Environment
  ansible.controller.execution_environment:
    name: Cloud EE
    description: Red Hat Cloud Services EE
    organization: Default
    image: quay.io/scottharwell/cloud-ee:latest
    pull: always
    state: present
    